FROM python:3.6.4

# Install deps
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean       

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements 
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# Add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# Add application files
COPY . /usr/src/app

# Run server
CMD ["./entrypoint.sh"]